_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.11.9
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
config:
    value:
        backup: null
        batch_size: 1
        datasets:
            test:
                parameters:
                    augmentations: []
                    dataset: tusimple
                    img_size:
                        - 360
                        - 640
                    max_lanes: 5
                    normalize: true
                    root: D:/manga/nckh_polylanenet/TUSimple/train_set
                    split: val
                type: LaneDataset
            train:
                parameters:
                    aug_chance: 0.9090909090909091
                    augmentations:
                        - name: Affine
                          parameters:
                            rotate:
                                - -10
                                - 10
                        - name: HorizontalFlip
                          parameters:
                            p: 0.5
                        - name: CropToFixedSize
                          parameters:
                            height: 648
                            width: 1152
                    dataset: tusimple
                    img_size:
                        - 360
                        - 640
                    normalize: true
                    root: D:/manga/nckh_polylanenet/TUSimple/train_set
                    split: train
                type: LaneDataset
            val:
                parameters:
                    augmentations: []
                    dataset: tusimple
                    img_size:
                        - 360
                        - 640
                    max_lanes: 5
                    normalize: true
                    root: D:/manga/nckh_polylanenet/TUSimple/train_set
                    split: val
                type: LaneDataset
        epochs: 2695
        exps_dir: experiments
        iter_log_interval: 1
        iter_time_window: 100
        loss_parameters:
            cls_weight: 0
            conf_weight: 1
            lower_weight: 1
            poly_weight: 1000
            upper_weight: 1
        lr_scheduler:
            name: CosineAnnealingLR
            parameters:
                T_max: 385
        model:
            name: PolyRegression
            parameters:
                backbone: mobilenet_v2
                curriculum_steps:
                    - 0
                    - 0
                    - 0
                    - 0
                num_outputs: 35
                pred_category: false
                pretrained: true
        model_save_interval: 1
        optimizer:
            name: Adam
            parameters:
                lr: 0.0003
        seed: 1
        test_parameters:
            conf_threshold: 0.5
config_str:
    value: |
        # Training settings
        exps_dir: 'experiments'
        iter_log_interval: 1
        iter_time_window: 100
        model_save_interval: 1
        seed: 1
        backup:
        model:
          name: PolyRegression
          parameters:
            num_outputs: 35 # (5 lanes) * (1 conf + 2 (upper & lower) + 4 poly coeffs)
            pretrained: true
            backbone: 'mobilenet_v2'
            pred_category: false
            curriculum_steps: [0, 0, 0, 0]
        loss_parameters:
          conf_weight: 1
          lower_weight: 1
          upper_weight: 1
          cls_weight: 0
          poly_weight: 1000
        batch_size: 1
        epochs: 2695
        optimizer:
          name: Adam
          parameters:
            lr: 3.0e-4
        lr_scheduler:
          name: CosineAnnealingLR
          parameters:
            T_max: 385


        # Testing settings
        test_parameters:
          conf_threshold: 0.5

        # Dataset settings
        datasets:
          train:
            type: LaneDataset
            parameters:
              dataset: tusimple
              split: train
              img_size: [360, 640]
              normalize: true
              aug_chance: 0.9090909090909091 # 10/11
              augmentations:
               - name: Affine
                 parameters:
                   rotate: !!python/tuple [-10, 10]
               - name: HorizontalFlip
                 parameters:
                   p: 0.5
               - name: CropToFixedSize
                 parameters:
                   width: 1152
                   height: 648
              root: "D:/manga/nckh_polylanenet/TUSimple/train_set"

          test: &test
            type: LaneDataset
            parameters:
              dataset: tusimple
              split: val
              max_lanes: 5
              img_size: [360, 640]
              root: "D:/manga/nckh_polylanenet/TUSimple/train_set"
              # D:\manga\nckh_polylanenet\TUSimple\train_set
              normalize: true
              augmentations: []

          # val = test
          val:
            <<: *test
